# Generated by Django 4.0.8 on 2023-01-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.department'),
        ),
        migrations.AddField(
            model_name='committee',
            name='member',
            field=models.ManyToManyField(to='meetings.member'),
        ),
    ]
