# Generated by Django 4.0.8 on 2023-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_end_time_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='acknowledged_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='acknowledged_member', to='meetings.member'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attended_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='attended_member', to='meetings.member'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invited_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_member', to='meetings.member'),
        ),
    ]
