# Generated by Django 4.0.8 on 2023-01-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_committee_member_alter_member_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.department'),
        ),
    ]
