# Generated by Django 4.0.8 on 2023-01-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meetingtype_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtype',
            old_name='description',
            new_name='meeting_type_description',
        ),
    ]
