# Generated by Django 4.0.8 on 2023-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='content_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
